POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFuYW5hcyIsImlkIjoiNjgyNzU3ZWYxZDE4NWZkN2Y0ZjcxOGM4IiwiaWF0IjoxNzQ3NDA5MTY3fQ.mlt7HcwEEyhN9iQnSbcadRoXtjL9_i9wqbSf9lS8AkE
{
    "title": "Da Blog",
    "author": "DaBlogger",
    "url": "dablog.com",
    "likes": 69
}